exec-once = waybar
exec-once = hypridle
exec-once = swaync
exec-once = swaybg -i ~/.config/zeros/theme/currentwallpaper.png
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = hyprctl setcursor Bibata-Modern-Ice 24
